FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 8080
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
RUN pip install requests
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
RUN pip install requests
RUN pip install python-firebase
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
RUN pip install requests
RUN pip install python-firebase
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
RUN pip install requests
RUN pip install python-firebase
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
RUN pip install requests
RUN pip install python-firebase
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
RUN pip install git+https://github.com/ozgur/python-firebase
RUN pip install requests
RUN pip install python-firebase
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
RUN pip install git+https://github.com/ozgur/python-firebase
RUN pip install requests
RUN pip install python-firebase
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
FROM python
RUN pip install flask
RUN pip install flask_bootstrap
RUN pip install flask_wtf
RUN pip install flask_sqlalchemy
RUN pip install flask_login
RUN pip install email_validator
RUN pip install git+https://github.com/ozgur/python-firebase
RUN pip install requests
RUN pip install python-firebase
COPY  ./static /home/myapp/static/
COPY  ./templates /home/myapp/templates/
COPY  app.py /home/myapp/
COPY  database.db /home/myapp/
EXPOSE 5000
CMD python3 /home/myapp/app.py
